name: intro_python
channels:
    - defaults
    - plotly
dependencies:
    - python=3.7.2
    - scipy=1.2.0
    - numpy=1.15.4
    - pandas=0.24.1
    - matplotlib=3.0.2
    - scikit-learn=0.20.2
    - plotly=3.5.0
    - jupyter=1.0.0
    - notebook=5.7.4
    - jupyterlab=0.35.3
    - ipywidgets=7.4.2
    
